---
# Bastion Host
bastion_host: 192.168.11.10
bastion_user: ubuntu
bastion_ssh_private_key_file: ~/.ssh/keys/id_ed25519
bastion_port: 2222
ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ bastion_ssh_private_key_file }} -p {{ bastion_port }} {{ bastion_user }}@{{ bastion_host }} -W %h:%p"'
# Target Host
ansible_host: 192.168.122.70
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/keys/id_ed25519
# ansible_ssh_pass: {{ vault_ansible_ssh_pass }}
ansible_port: 2222
